version: "3"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: transcendence-frontend:latest
    container_name: frontend
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL:-http://localhost}
    networks:
      - transcendence
    depends_on:
      - backend
    expose:
      - 80
    ports:
      - 80:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: transcendence-backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - uploads_volumes:/app/uploads
    networks:
      - transcendence
    depends_on:
      - db
    expose:
      - 3000
    ports:
      - 3000:3000
  db:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - db_volumes:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - transcendence
networks:
  transcendence:
    driver: bridge
volumes:
  db_volumes:
    name: ft_tsen_db_volumes
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/transcendence/data/postgresql/
  uploads_volumes:
    name: ft_tsen_uploads_volumes
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${HOME}/transcendence/data/upload/
